### ISSUE TITLE
List of team member

### ISSUE THREAD

**Issue by congnguyen1428** [economicanalysiswithmatrices/BestProjects20152016#2]
Dear @meleantonio ,
I would like to contact the members who did this project last year so we can ask them for some advice on this project directly, however, I cannot find their names in those files. Can you provide me their email addresses, please?
Thank you very much.
Kind regards,

Cong Nguyen

**Comment by meleantonio** [comment]
@congnguyen1428 the names are in the report, just download it:

https://github.com/economicanalysiswithmatrices/BestProjects20152016/blob/master/Group%203%20-%20Who%20Wants%20to%20Be%20a%20Millionaire/Report%20and%20Instructions.docx

**Comment by meleantonio** [comment]
@congnguyen1428 the names are in the report, just download it:

https://github.com/economicanalysiswithmatrices/BestProjects20152016/blob/master/Group%203%20-%20Who%20Wants%20to%20Be%20a%20Millionaire/Report%20and%20Instructions.docx
