### ISSUE TITLE
Global variable

### ISSUE THREAD

**Issue by congnguyen1428** [economicanalysiswithmatrices/BestProjects20152016#3]
Dear @meleantonio,
I have a question about the global variable. In the file A_Callback in group 3 project, on the lines of 74 & 75 of the file, they mentioned about the global variable and how it connect to the GUI. My question is what does those two lines of code mean and why they put them from the question 2 onwards? Should it appear at the beginning of the file?
Thank you very much.
Kind regards,

Cong Nguyen

**Comment by meleantonio** [comment]
@congnguyen1428 as far as I understand,they use a global variable to store at what point of the game they are. if you answer incorrectly upto question 5, you win nothing,hence they reset the game to start from question 1. However, from question 6, if you answer incorrectly the game ends but you go home with what you won until question 6, hence they reset the winnings to question 6 winning by using global_struct. 

Are you familiar with global variables? They are variables that are visible and shared to all functions that declare them as global.

**Comment by congnguyen1428** [comment]
Dear @meleantonio ,
- If the global variables can be shared to all functions then do I need to keep repeating them in local function? When I run the file, Matlab keeps telling me there is an error if the global variables appear a lot of time.
- Also, is the global variable in this case represent the money in the question?
Thank you very much.
Kind regards,

Cong Nguyen

**Comment by meleantonio** [comment]
@congnguyen1428 no, local functions will see the global variable of the
main function.
I think the global variable global_struct tells the code to keep track of the
winnings is some way.

**Comment by congnguyen1428** [comment]
Dear @meleantonio ,

Sorry for bothering you, again, but I just want a further clarification. In the local functions, if I want the global to appear then I just need to type "global=round1" for instance?

Thank you.
Kind regards,

Cong Nguyen

**Comment by meleantonio** [comment]
@congnguyen1428 can you provide me with a full example? The syntax to declare some variables as global is

```matlab
`global variable1 variable2 variable3`

**Comment by congnguyen1428** [comment]
Dear @meleantonio 
In the original file, the guys did this:
```matlab
if question == 8  % If question is number 8
    if rightanswer == 1 % If the correct answer is B
        set(handles.result,'String','You had £4000...') % Displays the string 
        pause(1) % Pause between string display
        set(handles.result,'String','and you just doubled it!') % Displays the string
        set(handles.pushbutton14,'visible','on'); % Makes the continue push button visible
    elseif rightanswer == 0 % However, if the answer is incorrect
        set(handles.result,'String','You just lost £3000. Unlucky, you walk away with £1000. Bad luck!') % Displays the string
        set(handles.pushbutton27,'visible','on') % Makes the replay push button visible
        question = 6
        **global global_struct
        global_struct.question = question**
    end
end
```

However, if I change like this, is that ok?
```matlab
if question == 8  % If question is number 8
    if rightanswer == 1 % If the correct answer is B
        set(handles.result,'String','You had £4000...') % Displays the string 
        pause(1) % Pause between string display
        set(handles.result,'String','and you just doubled it!') % Displays the string
        set(handles.pushbutton14,'visible','on'); % Makes the continue push button visible
    elseif rightanswer == 0 % However, if the answer is incorrect
        set(handles.result,'String','You just lost £3000. Unlucky, you walk away with £1000. Bad luck!') % Displays the string
        set(handles.pushbutton27,'visible','on') % Makes the replay push button visible
        question = 6
        **global = question**
    end
end
```

Thank you very much.
Kind regards,

Cong Nguyen

**Comment by meleantonio** [comment]
@congnguyen1428 no. 

global is a keyword for declaring a variable as global. In the way in which you are writing it, Matlab will understand that global is a variable and that you are assigning this variable the value contained in the variable question.

**Comment by congnguyen1428** [comment]
Dear @meleantonio 
So if I mentioned the global variable at the beginning of the file, do I need to repeat it in each local function like the guy did above?
Thank you.

Cong Nguyen

**Comment by meleantonio** [comment]
@congnguyen1428 Oh i see what you mean by local function. Yes, you should.

**Comment by congnguyen1428** [comment]
@meleantonio 
But when I include them in those local function, Matlab keeps telling me there is an error and it does not let me run the file unless all of the line "global global_struct" being deleted. Can you check this for me, please?
Thank you.

Cong Nguyen

**Comment by meleantonio** [comment]
@congnguyen1428 the code for this project works just fine for me... no idea...

**Comment by meleantonio** [comment]
@congnguyen1428  it turns out that using global variables in GUIs is a bad idea, I've done some research. The general recommendation seems to be to define a new field in the handles structure, and then update them using guidata. There are a few examples online if you google "global variable GUI matlab". Sorry about this, I had no idea.
